package view;
// @author Clayton A. Magaton
import dao.ConexaoBD;

public class TPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    public TPrincipal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBackEnd = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMCadastro = new javax.swing.JMenu();
        jMIPacientes = new javax.swing.JMenuItem();
        jMIMedicos = new javax.swing.JMenuItem();
        jMIEnfermagem = new javax.swing.JMenuItem();
        jMIUsuarios = new javax.swing.JMenuItem();
        jMICbo = new javax.swing.JMenuItem();
        jMRelatorios = new javax.swing.JMenu();
        jMFerramentas = new javax.swing.JMenu();
        jMIBemVindo = new javax.swing.JMenuItem();
        jMISair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jBackEnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imganes/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jBackEnd);
        jBackEnd.setBounds(0, 0, 1310, 610);

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(189, 30));

        jMCadastro.setText("Cadastro");
        jMCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMIPacientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIPacientes.setText("Pacientes");
        jMIPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPacientesActionPerformed(evt);
            }
        });
        jMCadastro.add(jMIPacientes);

        jMIMedicos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIMedicos.setText("Médicos");
        jMCadastro.add(jMIMedicos);

        jMIEnfermagem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIEnfermagem.setText("Enfermagem");
        jMIEnfermagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIEnfermagemActionPerformed(evt);
            }
        });
        jMCadastro.add(jMIEnfermagem);

        jMIUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMIUsuarios.setText("Usuários");
        jMIUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIUsuariosActionPerformed(evt);
            }
        });
        jMCadastro.add(jMIUsuarios);

        jMICbo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMICbo.setText("CBO");
        jMICbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICboActionPerformed(evt);
            }
        });
        jMCadastro.add(jMICbo);

        jMenuBar1.add(jMCadastro);

        jMRelatorios.setText("Relatórios");
        jMRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuBar1.add(jMRelatorios);

        jMFerramentas.setText("Ferramentas");
        jMFerramentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMIBemVindo.setText("Bem Vindos");
        jMIBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIBemVindoActionPerformed(evt);
            }
        });
        jMFerramentas.add(jMIBemVindo);

        jMISair.setText("Sair");
        jMISair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISairActionPerformed(evt);
            }
        });
        jMFerramentas.add(jMISair);

        jMenuBar1.add(jMFerramentas);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1331, 670));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMISairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMISairActionPerformed

    private void jMIBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIBemVindoActionPerformed

    }//GEN-LAST:event_jMIBemVindoActionPerformed

    private void jMIUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIUsuariosActionPerformed
       new TCadUsuario().setVisible(true);
    }//GEN-LAST:event_jMIUsuariosActionPerformed

    private void jMIEnfermagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIEnfermagemActionPerformed
        new TCadEnfermagem().setVisible(true);
    }//GEN-LAST:event_jMIEnfermagemActionPerformed

    private void jMICboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICboActionPerformed
       new TCadCbo().setVisible(true);
    }//GEN-LAST:event_jMICboActionPerformed

    private void jMIPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPacientesActionPerformed
        new TCadPaciente().setVisible(true);
    }//GEN-LAST:event_jMIPacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackEnd;
    private javax.swing.JMenu jMCadastro;
    private javax.swing.JMenu jMFerramentas;
    private javax.swing.JMenuItem jMIBemVindo;
    private javax.swing.JMenuItem jMICbo;
    private javax.swing.JMenuItem jMIEnfermagem;
    private javax.swing.JMenuItem jMIMedicos;
    private javax.swing.JMenuItem jMIPacientes;
    private javax.swing.JMenuItem jMISair;
    private javax.swing.JMenuItem jMIUsuarios;
    private javax.swing.JMenu jMRelatorios;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
